import { promises as fs } from 'node:fs'
import path from 'node:path'

const WIN_SUBFOLDER = 'WinCalendar'
const TIMELINE_FILENAME = 'timeline-life.md'
const STATE_FILENAME = '.state.json'
const JOURNAL_SUBFOLDER = 'journal'

export type PersistedWin = {
  /** Stable id used as the key in .state.json and for the calendar cell. */
  id: string
  /** ISO YYYY-MM-DD the win is placed on. */
  date: string
  title: string
  whatHappened: string
  lifeImpact: string
  whyItMatters: string
  /** ISO timestamp when the win becomes visible to the UI and the email is sent. */
  revealAt: string
  /** Resend email id once scheduled, so we can cancel/update later if we add that. */
  scheduledEmailId?: string
}

type StateFile = {
  version: 1
  wins: Record<string, { revealAt: string; scheduledEmailId?: string }>
}

function winCalendarDir(obsidianPath: string): string {
  return path.join(obsidianPath, WIN_SUBFOLDER)
}

function timelinePath(obsidianPath: string): string {
  return path.join(winCalendarDir(obsidianPath), TIMELINE_FILENAME)
}

function statePath(obsidianPath: string): string {
  return path.join(winCalendarDir(obsidianPath), STATE_FILENAME)
}

function journalPath(obsidianPath: string, dateISO: string): string {
  return path.join(winCalendarDir(obsidianPath), JOURNAL_SUBFOLDER, `${dateISO}.md`)
}

export async function ensureVaultLayout(obsidianPath: string): Promise<void> {
  await fs.mkdir(path.join(winCalendarDir(obsidianPath), JOURNAL_SUBFOLDER), { recursive: true })
  const timeline = timelinePath(obsidianPath)
  try {
    await fs.access(timeline)
  } catch {
    const header =
      '# Life Timeline\n' +
      "*Generated by Win Calendar. Edit freely; the app parses `## <Date> — <Title>` headings.*\n\n---\n\n"
    await fs.writeFile(timeline, header, 'utf8')
  }
}

export async function readTimeline(obsidianPath: string): Promise<string> {
  try {
    return await fs.readFile(timelinePath(obsidianPath), 'utf8')
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') return ''
    throw error
  }
}

export async function appendJournalEntry(
  obsidianPath: string,
  dateISO: string,
  rawText: string,
): Promise<void> {
  await ensureVaultLayout(obsidianPath)
  const target = journalPath(obsidianPath, dateISO)
  const timestamp = new Date().toISOString()
  const divider = '\n\n---\n\n'
  const header = `## ${timestamp}\n\n`
  const body = rawText.trimEnd() + '\n'
  let existing = ''
  try {
    existing = await fs.readFile(target, 'utf8')
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  const next = existing ? existing.trimEnd() + divider + header + body : header + body
  await fs.writeFile(target, next, 'utf8')
}

/**
 * Formats a single win into the canonical `## <Date> — <Title>` block that the
 * frontend parser in `src/wins.ts` understands. The trailing `---` separator
 * matches the style used in `example/TIMELINE-finance.md`.
 */
export function renderWinBlock(win: PersistedWin): string {
  const [yearStr, monthStr, dayStr] = win.date.split('-')
  const monthNames = [
    'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun',
    'Jul', 'Aug', 'Sep', 'Oct', 'Nov', 'Dec',
  ]
  const monthName = monthNames[Number(monthStr) - 1] ?? monthStr
  const heading = `## ${monthName} ${Number(dayStr)}, ${yearStr} — ${win.title}`
  return (
    `${heading}\n` +
    `**What happened:** ${win.whatHappened.trim()}\n` +
    `**Life impact:** ${win.lifeImpact.trim()}\n` +
    `**Why it matters:** ${win.whyItMatters.trim()}\n\n---\n\n`
  )
}

export async function appendWinsToTimeline(
  obsidianPath: string,
  wins: PersistedWin[],
): Promise<void> {
  if (wins.length === 0) return
  await ensureVaultLayout(obsidianPath)
  const target = timelinePath(obsidianPath)
  let existing = ''
  try {
    existing = await fs.readFile(target, 'utf8')
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code !== 'ENOENT') throw error
  }
  const rendered = wins.map(renderWinBlock).join('')
  const next = (existing.trimEnd() + '\n\n' + rendered).trimStart()
  await fs.writeFile(target, next, 'utf8')
}

async function readState(obsidianPath: string): Promise<StateFile> {
  try {
    const raw = await fs.readFile(statePath(obsidianPath), 'utf8')
    const parsed = JSON.parse(raw) as StateFile
    if (parsed.version !== 1 || typeof parsed.wins !== 'object' || parsed.wins === null) {
      return { version: 1, wins: {} }
    }
    return parsed
  } catch (error: unknown) {
    if ((error as NodeJS.ErrnoException).code === 'ENOENT') {
      return { version: 1, wins: {} }
    }
    throw error
  }
}

async function writeState(obsidianPath: string, state: StateFile): Promise<void> {
  await ensureVaultLayout(obsidianPath)
  await fs.writeFile(statePath(obsidianPath), JSON.stringify(state, null, 2), 'utf8')
}

export async function recordWinState(
  obsidianPath: string,
  wins: PersistedWin[],
): Promise<void> {
  if (wins.length === 0) return
  const state = await readState(obsidianPath)
  for (const win of wins) {
    state.wins[win.id] = {
      revealAt: win.revealAt,
      scheduledEmailId: win.scheduledEmailId,
    }
  }
  await writeState(obsidianPath, state)
}

export async function getRevealAtMap(
  obsidianPath: string,
): Promise<Record<string, string>> {
  const state = await readState(obsidianPath)
  const result: Record<string, string> = {}
  for (const [id, entry] of Object.entries(state.wins)) {
    result[id] = entry.revealAt
  }
  return result
}

/**
 * Removes a single win from both `timeline-life.md` and `.state.json`.
 * The win block in the timeline is identified by matching the `## …` heading
 * line that contains the win id's title slug. We strip the entire block
 * (heading + body lines + trailing `---` separator).
 */
export async function deleteWin(obsidianPath: string, winId: string): Promise<void> {
  // 1. Remove from .state.json
  const state = await readState(obsidianPath)
  if (winId in state.wins) {
    delete state.wins[winId]
    await writeState(obsidianPath, state)
  }

  // 2. Remove the matching block from timeline-life.md.
  // A block looks like:
  //   ## Mon DD, YYYY — Title\n
  //   **What happened:** …\n
  //   **Life impact:** …\n
  //   **Why it matters:** …\n
  //   \n
  //   ---\n
  //   \n
  // We identify the right heading by re-slugifying each heading title and
  // comparing it against the winId (which is `<date>-<slug>`).
  const timelineSource = await readTimeline(obsidianPath)
  if (!timelineSource) return

  const lines = timelineSource.split('\n')
  const resultLines: string[] = []
  let skipUntilNextBlock = false

  for (let lineIndex = 0; lineIndex < lines.length; lineIndex++) {
    const line = lines[lineIndex]

    if (line.startsWith('## ')) {
      // Parse date + title from the heading to reconstruct the id.
      const headingBody = line.slice(3)
      // Split on em dash, en dash, or hyphen surrounded by spaces
      const dashMatch = headingBody.match(/^(.+?)\s+[\u2014\u2013-]\s+(.+)$/)
      if (dashMatch) {
        const datePart = dashMatch[1].trim()
        const titlePart = dashMatch[2].trim()
        const slugifiedTitle = titlePart
          .toLowerCase()
          .replace(/[^a-z0-9]+/g, '-')
          .replace(/^-+|-+$/g, '')
          .slice(0, 60)
        // Reconstruct the date portion into YYYY-MM-DD to match the id format.
        const parsedDate = parseDateHeading(datePart)
        if (parsedDate) {
          const candidateId = `${parsedDate}-${slugifiedTitle}`
          if (candidateId === winId) {
            skipUntilNextBlock = true
            // Also consume the trailing `---` separator block (blank + --- + blank).
            // We'll skip lines until we've consumed through the next `---`.
            continue
          }
        }
      }
      skipUntilNextBlock = false
    }

    if (skipUntilNextBlock) {
      // Skip body lines. Stop skipping after we've passed the `---` separator.
      if (line.trim() === '---') {
        skipUntilNextBlock = false
      }
      continue
    }

    resultLines.push(line)
  }

  const updated = resultLines.join('\n').replace(/\n{3,}/g, '\n\n').trimEnd() + '\n'
  await fs.writeFile(timelinePath(obsidianPath), updated, 'utf8')
}

/** Parses a heading date like "Apr 23, 2026" into "2026-04-23". */
function parseDateHeading(datePart: string): string | null {
  const monthNames: Record<string, string> = {
    Jan: '01', Feb: '02', Mar: '03', Apr: '04', May: '05', Jun: '06',
    Jul: '07', Aug: '08', Sep: '09', Oct: '10', Nov: '11', Dec: '12',
  }
  const match = datePart.match(/^(\w{3})\s+(\d{1,2}),\s+(\d{4})$/)
  if (!match) return null
  const month = monthNames[match[1]]
  if (!month) return null
  const day = match[2].padStart(2, '0')
  return `${match[3]}-${month}-${day}`
}
